name: Run Main.py Once a Day

on:
  schedule:
    # Run once a day at midnight (UTC)
    - cron: '0 18 * * *'  #20:00 Paris time
  workflow_dispatch: # Allows manual trigger from the GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome
      run: |
        sudo apt update
        sudo apt install -y wget gnupg2
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
        sudo apt update
        sudo apt install -y google-chrome-stable

    - name: Set up Google API credentials
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: echo "$GOOGLE_CREDENTIALS" > credentials.json

    - name: Run script
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python main.py
